"""Read-only historical G/V audit; no replay, estimator change or GT feedback."""
import argparse
from collections import Counter
import csv
import hashlib
import json
from pathlib import Path
import sys

import numpy as np
from scipy.spatial.transform import Rotation

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / 'scripts/ltv_gv_diagnosis'))
from analyze import body, reference, nearest, stats, labels
sys.path.insert(0, str(ROOT / 'scripts/ltv_gv_evaluation'))
from evaluate import align

SEQS = ('V2_02_medium', 'V2_03_difficult')
MODES = ('OFF', 'G', 'V', 'GV')


def sha(path):
    h = hashlib.sha256()
    with path.open('rb') as f:
        for b in iter(lambda: f.read(1024*1024), b''):
            h.update(b)
    return dict(sha256=h.hexdigest(), bytes=path.stat().st_size)


def load(path):
    return [json.loads(x) for x in path.read_text().splitlines() if x]


def write(path, data):
    path.write_text(json.dumps(data, indent=2, allow_nan=False)+'\n')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--evidence', type=Path, default=Path('/home/he/output/ltv_gv_fusion_evaluation_20261005'))
    ap.add_argument('--out', type=Path, default=ROOT/'docs/ltv/landmark_correlation/gv')
    args = ap.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    frozen = json.loads((ROOT/'docs/ltv/gv_no_benefit_diagnosis/read_manifest.json').read_text())
    identities = []
    for path, expected in frozen.items():
        p = Path(path)
        actual = sha(p) if p.exists() else None
        identities.append(dict(path=str(p), expected=expected, actual=actual,
                               status='PASS' if actual == expected else 'FAIL'))
        print('hashed', p.name, p.parent.name, flush=True)
    external = json.loads((ROOT/'docs/ltv/gv_fusion_evaluation/evidence/external_manifest.json').read_text())['files']
    for seq in SEQS:
        for mode in MODES:
            suffix = '01' if mode == 'GV' else '03'
            run = args.evidence/'runs'/f'{seq}_{mode}_{suffix}'
            for name in ('trajectory.csv','effective_options.json','identity.json','replay.json'):
                path = run/name
                expected = external[str(path.relative_to(args.evidence))]
                actual = sha(path)
                identities.append(dict(path=str(path), expected=expected, actual=actual,
                                       status='PASS' if actual == expected else 'FAIL'))
            identity = json.loads((run/'identity.json').read_text())
            inp = identity['input_identity']
            for name, expected_sha in inp['config_sha'].items():
                path = Path(inp['config']).parent/name
                actual = sha(path)
                identities.append(dict(path=str(path), expected_sha256=expected_sha,actual=actual,
                                       status='PASS' if actual['sha256']==expected_sha else 'FAIL'))
            for sensor in inp['sensors'].values():
                path = Path(sensor['path'])
                actual = sha(path)
                identities.append(dict(path=str(path), expected_sha256=sensor['sha256'],actual=actual,
                                       status='PASS' if actual['sha256']==sensor['sha256'] else 'FAIL'))
    write(args.out/'raw_identity.json', identities)
    if any(x['status'] != 'PASS' for x in identities):
        raise RuntimeError('Historical raw identity mismatch: cannot reuse derived evidence')
    # Freeze intervals using OFF only. New ON is never generated by this program.
    intervals, data, result_rows, event_rows, completeness = {}, {}, [], [], {}
    source_inputs = json.loads((args.evidence/'freeze.json').read_text())['inputs']
    historical = json.loads((ROOT/'docs/ltv/gv_fusion_evaluation/metrics.json').read_text())
    local_inputs = {}
    for seq in SEQS:
        data[seq] = {}
        for mode in MODES:
            suffix = '01' if mode == 'GV' else '03'
            run = args.evidence/'runs'/f'{seq}_{mode}_{suffix}'
            f, e = load(run/'features.jsonl'), load(run/'fusion.jsonl')
            x = np.loadtxt(run/'trajectory.csv', delimiter=',', skiprows=1)
            assert [z['camera_ns'] for z in f] == [z['camera_ns'] for z in e]
            meta = json.loads((run/'replay.json').read_text())
            assert meta['complete'] and meta['short_limit_seconds']==0
            assert meta['camera_packets']==meta['input_camera_packets']==len(e)
            assert meta['imu_consumed']==meta['input_imu_samples']
            assert meta['output_rows']==len(x)
            applied = {b:sum(bool(z['consumed'] and z[b+'_rows'] and z['submit_reason']=='joint_applied' and z['ekf_calls']==1) for z in e) for b in ('G','V')}
            assert all(applied[b]==meta['actual_'+b+'_submissions'] for b in ('G','V'))
            completeness[seq+'/'+mode] = dict(complete=True,camera_packets=len(e),imu_samples=meta['imu_consumed'],
                output_rows=len(x),actual_G=applied['G'],actual_V=applied['V'])
            data[seq][mode] = (run, f, e, x)
        offrun, of, oe, ox = data[seq]['OFF']
        for mode in MODES:
            events=data[seq][mode][2]
            assert len(events)==len(oe)
            first={}
            for key in ('main_digest','covariance_digest','observer_digest'):
                divergence=next((z for z,o in zip(events,oe) if z[key]!=o[key]),None)
                if divergence is not None and key!='observer_digest':
                    assert divergence['consumed'] and divergence['submit_reason']=='joint_applied' and divergence['ekf_calls']==1
                    assert divergence['G_rows'] or divergence['V_rows']
                first[key]=divergence['camera_ns'] if divergence is not None else None
            completeness[seq+'/'+mode]['first_divergence']=first
        gtpath = Path(source_inputs[seq]['root'])/'state_groundtruth_estimate0/data.csv'
        gt = np.loadtxt(gtpath, delimiter=',', comments='#')
        t = np.array([r['target_imu_time'] for r in of])
        v, g, valid = reference(gt, t)
        initialized = np.array([bool(r['initialized']) for r in of])
        support = initialized & valid
        ix = nearest(ox[:, 0], t)
        support &= abs(ox[ix, 0]-t) <= 1e-6
        ov, og = body(ox[ix, 1:])
        err = {'V':np.linalg.norm(ov-v, axis=1), 'G':np.degrees(np.arccos(np.clip(np.sum(og*g, axis=1), -1, 1)))}
        visual = np.array([r['visual_rows'] for r in oe])
        weak = visual <= np.quantile(visual[support], .2)
        masks = {'full':support, 'weak_visual_OFF':support & weak}
        before = nearest(t, t-1.)
        for b in ('G', 'V'):
            ready = np.array([bool(r['ready_'+b]) for r in of])
            lab = labels(ready & initialized, weak)
            high = support & (err[b] >= np.quantile(err[b][support], .75))
            masks[b+'_rising_high_OFF'] = high & (abs(t[before]-(t-1.))<=.025) & initialized[before] & (err[b]>err[b][before])
            masks[b+'_interruption_OFF'] = support & (lab=='interruption')
        # Explicit masks preserve disjoint high-error samples; no ON-dependent window selection.
        intervals[seq] = dict(origin_s=float(t[0]), times_s=t.tolist(),
            masks={k:np.flatnonzero(m).tolist() for k,m in masks.items()},
            contract_source='docs/ltv/gv_no_benefit_diagnosis/protocol.md',
            weak_visual_threshold=float(np.quantile(visual[support], .2)))
        local_inputs[seq] = (t, gt, masks, v)
    write(args.out/'completeness.json', completeness)
    write(args.out/'frozen_intervals.json', intervals)
    write(args.out/'evaluation_contract.json', dict(version=1, purpose='retrospective revalidation of frozen historical ON; no new ON',
        global_fraction=.005, local_fraction=.02, absolute={'ATE_m':.001,'RPE_translation_m':.001,'RPE_rotation_deg':.01,'velocity_mps':.005},
        local_absolute_factor=2, interval_source_sha256=sha(ROOT/'docs/ltv/gv_no_benefit_diagnosis/protocol.md')['sha256'],
        alignment='per mode full-support SE3, no scale; unchanged historical evaluator',
        local_alignment='reuse each mode full-support SE3; never refit local windows',
        rpe_local='both endpoints must belong to frozen mask; may be NOT_EVALUATED if empty',
        velocity_reference='published EuRoC GT velocity transformed to body; SLERP orientation, linear velocity, bracket <=10ms',
        timing='GT nearest <=20ms for pose; trajectory match <=1us; RPE endpoints <=25ms',
        forbidden='synthetic confidence from deterministic replays; changing thresholds after results'))
    recomputed = {}
    for seq in SEQS:
        t, gt, masks, gt_v = local_inputs[seq]
        off = data[seq]['OFF'][3]
        # Historical evaluator pose support: fixed OFF initialized camera samples within GT coverage.
        support = t[t >= off[0,0]-1e-6]
        gi = nearest(gt[:,0]*1e-9, support)
        inside = (support >= gt[0,0]*1e-9) & (support <= gt[-1,0]*1e-9) & (abs(gt[gi,0]*1e-9-support)<=.02)
        pt, gp, gq = support[inside], gt[gi[inside],1:4], gt[gi[inside]][:,[5,6,7,4]]
        mask_index = nearest(t, pt)
        for mode in MODES:
            run,f,e,x = data[seq][mode]
            xi = nearest(x[:,0], pt)
            assert np.all(abs(x[xi,0]-pt)<=1e-6)
            est = x[xi]
            r, trans = align(gp, est[:,5:8])
            pe = np.linalg.norm(est[:,5:8]@r.T+trans-gp, axis=1)
            re, rg = Rotation.from_quat(est[:,1:5]), Rotation.from_quat(gq)
            vi = nearest(x[:,0], t)
            ev, _ = body(x[vi,1:])
            ve = np.linalg.norm(ev-gt_v, axis=1)
            own_t = np.array([r['target_imu_time'] for r in f])
            assert np.array_equal(own_t,t)
            for region, m in masks.items():
                pm = m[mask_index]
                values = [('ATE_m',pe[pm],.001),('velocity_mps',ve[m],.005)]
                for dt in (1.,5.):
                    end = nearest(pt, pt+dt)
                    ok = (abs(pt[end]-(pt+dt))<=.025) & pm & pm[end]
                    a,b = np.flatnonzero(ok),end[ok]
                    de = re[a].inv().apply(est[b,5:8]-est[a,5:8])
                    dg = rg[a].inv().apply(gp[b]-gp[a])
                    dre = ((rg[a].inv()*rg[b]).inv()*(re[a].inv()*re[b])).magnitude()
                    values += [(f'RPE_{int(dt)}s_m',np.linalg.norm(de-dg,axis=1),.001),
                               (f'RPE_{int(dt)}s_deg',np.degrees(dre),.01)]
                for metric, values, absolute in values:
                    finite = values[np.isfinite(values)]
                    rms = float(np.sqrt(np.mean(finite**2))) if len(finite) else None
                    key=(seq,region,metric)
                    if mode == 'OFF': recomputed[key]=rms
                    base = recomputed[key]
                    tolerance = max((.005 if region=='full' else .02)*base,absolute*(1 if region=='full' else 2)) if base is not None else None
                    delta = rms-base if rms is not None and base is not None else None
                    status = 'NOT_EVALUATED' if delta is None else ('PASS_WITHIN_SCOPE' if delta<=tolerance else 'FAIL')
                    result_rows.append(dict(sequence=seq,mode=mode,region=region,metric=metric,samples=len(finite),
                        off=base,value=rms,delta=delta,allowed_worsening=tolerance,status=status))
                    if region=='full' and metric!='velocity_mps':
                        old = next(z for z in historical if z['sequence']==seq and z['mode']==mode)
                        expected = old['ate_rmse_m'] if metric=='ATE_m' else old['rpe'][str(float(metric[4]))]['rotation_rmse_deg' if metric.endswith('deg') else 'translation_rmse_m']
                        assert abs(rms-expected)<1e-12, (seq,mode,metric,rms,expected)
            for b in ('G','V'):
                actual=np.array([bool(z['consumed'] and z[b+'_rows'] and z['submit_reason']=='joint_applied' and z['ekf_calls']==1) for z in e])
                for region,m in masks.items():
                    reasons=Counter(z[b+'_reason'] if z['receipt'] else 'no_update_stage:'+z['trigger_reason'] for z,keep in zip(e,m) if keep and z['requested_'+b])
                    event_rows.append(dict(sequence=seq,mode=mode,branch=b,region=region,frames=int(m.sum()),
                        available=int(sum(bool(z['available']) and keep for z,keep in zip(f,m))),
                        valid=int(sum(bool(z['observer_valid']) and keep for z,keep in zip(f,m))),
                        ready=int(sum(bool(z['ready_'+b]) and keep for z,keep in zip(f,m))),
                        requested=int(sum(bool(z['requested_'+b]) and keep for z,keep in zip(e,m))),
                        gates=int(sum(z[b+'_nis']>=0 and keep for z,keep in zip(e,m))),
                        accepted=int(sum(z[b+'_reason']=='accepted' and keep for z,keep in zip(e,m))),
                        applied=int((actual&m).sum()),reasons=json.dumps(reasons,sort_keys=True)))
    for name, rows in [('metrics.csv',result_rows),('events.csv',event_rows)]:
        with (args.out/name).open('w') as f:
            w=csv.DictWriter(f,fieldnames=rows[0].keys(),lineterminator="\n");w.writeheader();w.writerows(rows)
    write(args.out/'summary.json',dict(raw_files_verified=len(identities),new_replays=0,full_metrics_exact_historical=True,
        failing_precision_rows=[r for r in result_rows if r['status']=='FAIL'],
        incomplete_precision_rows=[r for r in result_rows if r['status']=='NOT_EVALUATED'],
        code_identity=sha(Path(__file__)),statistics='NOT_ACHIEVED',benefit='NOT_DEMONSTRATED',
        performance='NOT_EVALUATED: archived diagnostic I/O and concurrent/resource context cannot certify production p95/RSS',
        scope='G/V historical V2_02/V2_03 configuration only; does not validate new shadow build'))
    print('audit complete',flush=True)


if __name__ == '__main__':main()
