"""Fixed evaluator-cadence and pool-support diagnosis only; no decision edits."""
import argparse,json,sys,hashlib
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from real_evaluate import episodes
import numpy as np
p=argparse.ArgumentParser();p.add_argument('evaluation');args=p.parse_args();d=Path(args.evaluation);m=json.loads((d/'metrics.json').read_text());a=dict(np.load(d/'error_curves.npz'));t=a['time'];epoch=a['P_NEW_epoch'];lookup={r['camera_ns']:r for r in map(json.loads,(Path(m['provenance']['runs']['P_NEW'])/'features.jsonl').read_text().splitlines())};r=[lookup[int(k)] for k in a['camera_ns']];raw=a['P_NEW_finite_current'];pool=np.array([bool(x['pool_ready']) and x['observed_features']>=15 and x['mature_features']>=15 for x in r]);actual=a['P_NEW_ready_G']&a['P_NEW_ready_V'];supports={}
for name,mask in [('all_initialized',np.ones(len(t),bool)),('legal_current',raw),('observed_at_least15',raw&np.array([x['observed_features']>=15 for x in r])),('fixed_pool_current_mature15',raw&pool),('actual_joint',actual)]:
 ep=episodes(t,mask,epoch);supports[name]={'longest_seconds':max((e['duration'] for e in ep),default=0),'episodes_at_least5s':[e for e in ep if e['duration']>=5],'all_episodes':ep}
maxep=max(supports['actual_joint']['all_episodes'],key=lambda e:e['duration']);k=int(np.searchsorted(t,maxep['end']));neighbors=[]
for i in range(max(0,k-2),min(len(t),k+8)):
 x=r[i];neighbors.append({'relative_time':float(t[i]-t[0]),'time':float(t[i]),'camera_ns':int(a['camera_ns'][i]),'previous_delta_s':float(t[i]-t[i-1]) if i else None,'ready_G':x['ready_G'],'ready_V':x['ready_V'],'pool_ready':x['pool_ready'],'observed':x['observed_features'],'mature':x['mature_features'],'reason':x['reason'],'grace_G':x.get('grace_G'),'grace_V':x.get('grace_V')})
dt=np.diff(t);bins={str(round(float(v),2)):int(sum(np.abs(dt-v)<1e-5)) for v in np.unique(np.round(dt,2))};o={'sequence':m['sequence'],'status_unchanged':m['status'],'initialized_packets':len(t),'origin':float(t[0]),'median_cadence_seconds':float(np.median(dt)),'episode_gap_limit_seconds':1.5*float(np.median(dt)),'packet_gap_histogram_rounded_seconds':bins,'supports':supports,'longest_joint_end_neighbors':neighbors,'provenance':{'script_sha':hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),'curves_sha':hashlib.sha256((d/'error_curves.npz').read_bytes()).hexdigest()},'limitations':['Uses unchanged evaluator 1.5*median event-gap rule.','The multiplier is in evaluator source before R3, not explicitly numeric in goal/protocol/acceptance text.','Pool mask is necessary fixed online support, not a proof of geometric observability or accuracy.']};(d/'time_support_audit.json').write_text(json.dumps(o,indent=2)+'\n');print(json.dumps({'longest':{k:v['longest_seconds'] for k,v in supports.items()},'5s_pool_episodes':supports['fixed_pool_current_mature15']['episodes_at_least5s'],'cadence_histogram':bins,'end_neighbors':neighbors},indent=2))
